# Generated by Django 3.2.13 on 2022-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_name', models.CharField(default='', max_length=100)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(default='', max_length=100)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=998)),
                ('date', models.DateTimeField(editable=False)),
                ('message_id', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
    ]
