# Generated by Django 3.2.13 on 2022-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='date',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='to_name',
            field=models.CharField(default='', max_length=1),
        ),
    ]
