# Generated by Django 3.2.13 on 2022-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emaildata_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='from_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='to_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
