# Generated by Django 3.2.13 on 2022-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220629_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='to_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
